const state = { data:null, view:'today', query:'', focusFilter:'all', projectMode:'priority', selectedTask:null, selectedProject:null, connectionOpen:false };
const $ = (s,r=document)=>r.querySelector(s);
const $$ = (s,r=document)=>[...r.querySelectorAll(s)];
const esc = (v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));

async function api(action, payload={}){
  const opts = action ? {method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,...payload})} : {cache:'no-store'};
  const r=await fetch('/api/state',opts); if(!r.ok) throw new Error(await r.text()); return r.json();
}
function tasks(){return state.data?.tasks||[]} function projects(){return state.data?.projects||[]} function goals(){return state.data?.goals||[]} function milestones(){return state.data?.milestones||[]}
function project(id){return projects().find(p=>p.id===id)} function goal(id){return goals().find(g=>g.id===id)} function milestone(id){return milestones().find(m=>m.id===id)}
function openTasks(){return tasks().filter(t=>t.status!=='Done'&&t.status!=='Backlog')} function activeProjects(){return projects().filter(p=>!p.archived && !p.parentProjectId)}
function colorForTask(t){return project(t.projectId)?.color||'#62d6ff'}
function statusWeight(s){return s==='In Progress'?0:s==='Open'?1:s==='Waiting'?2:s==='Backlog'?3:4}
function projectTaskIds(p){const childIds=new Set([p.id,...projects().filter(x=>x.parentProjectId===p.id).map(x=>x.id)]);return tasks().filter(t=>childIds.has(t.projectId))}
function projectProgress(p){const all=projectTaskIds(p).filter(t=>t.status!=='Backlog');if(!all.length)return 0;return Math.round(all.filter(t=>t.status==='Done').length/all.length*100)}
function projectActiveCount(p){return projectTaskIds(p).filter(t=>['Open','In Progress','Waiting'].includes(t.status)).length}
function taskPath(t){const m=milestone(t.milestoneId),p=project(t.projectId),parent=p?.parentProjectId?project(p.parentProjectId):null,g=goal(t.goalId||p?.goalId||parent?.goalId);return [m?.title,p?.title,parent?.title,g?.title].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i)}
function unlockCount(t){return tasks().filter(x=>(x.dependsOn||[]).includes(t.id)).length}
function dependencyTitles(t){return (t.dependsOn||[]).map(id=>tasks().find(x=>x.id===id)?.title).filter(Boolean)}
function todayScore(t){if(t.status==='Done'||t.status==='Backlog')return -999;let s=0;if(t.todayRank!=null)s+=1000-Number(t.todayRank)*100;s+=(4-t.priority)*30;s+=unlockCount(t)*12;if(t.status==='In Progress')s+=18;if(t.status==='Waiting')s-=25;if(t.dueDate){const days=(new Date(t.dueDate)-new Date())/86400000;if(days<=1)s+=40;else if(days<=7)s+=18}return s}
function focusTasks(){const ranked=openTasks().sort((a,b)=>todayScore(b)-todayScore(a));const picked=[],areas=new Map();for(const t of ranked){const count=areas.get(t.area)||0;if(count>=2&&picked.length<4)continue;picked.push(t);areas.set(t.area,count+1);if(picked.length===5)break}return picked}
function matchesQuery(t){if(!state.query)return true;const q=state.query.toLowerCase();return [t.title,t.area,t.nextAction,t.waitingOn,project(t.projectId)?.title,...taskPath(t)].filter(Boolean).join(' ').toLowerCase().includes(q)}
function priorityLabel(p){return p===1?'High':p===2?'Medium':'Low'}
function dateLabel(){return new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date()).toUpperCase()}
function contextMeta(t){return `${t.status}${t.effort?` · ${t.effort}`:''}${t.dueText?` · ${t.dueText}`:''}`}

function render(){renderSidebar();renderNav();const root=$('#viewRoot');if(state.view==='today')root.innerHTML=renderToday();if(state.view==='projects')root.innerHTML=renderProjectsPage();if(state.view==='upcoming')root.innerHTML=renderTaskListPage('Upcoming','Tasks with timing or due dates',tasks().filter(t=>t.status!=='Done'&&(t.dueText||t.dueDate)).sort((a,b)=>a.priority-b.priority));if(state.view==='waiting')root.innerHTML=renderTaskListPage('Waiting','Everything currently blocked by someone or something',tasks().filter(t=>t.status==='Waiting'||t.waitingOn));if(state.view==='completed')root.innerHTML=renderTaskListPage('Completed','Recent finished work',tasks().filter(t=>t.status==='Done').sort((a,b)=>String(b.completedAt||b.updatedAt).localeCompare(String(a.completedAt||a.updatedAt))));bindView();}
function renderNav(){$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view))}
function renderSidebar(){const ps=activeProjects().sort((a,b)=>a.priority-b.priority);$('#sidebarProjects').innerHTML=ps.map(p=>`<button class="side-project" data-project="${esc(p.id)}">${esc(p.title)}</button>`).join('');$$('.side-project').forEach(b=>b.onclick=()=>openProject(b.dataset.project))}
function stats(){return {focus:focusTasks().length,active:tasks().filter(t=>['Open','In Progress'].includes(t.status)).length,waiting:tasks().filter(t=>t.status==='Waiting'||t.waitingOn).length,projects:activeProjects().filter(p=>projectActiveCount(p)>0).length}}
function renderToday(){const f=focusTasks().filter(matchesQuery);const s=stats();return `<div class="page"><section class="hero"><div><div class="eyebrow">${dateLabel()}</div><h1>What moves things forward today?</h1><p>A deliberately small mix of important, immediate, and diverse actions — with the larger project and outcome visible underneath.</p></div><div class="date-chip">${s.active} active across ${s.projects} projects</div></section><section class="stats"><div class="stat"><strong>${s.focus}</strong><span>focus tasks</span></div><div class="stat"><strong>${s.active}</strong><span>active tasks</span></div><div class="stat"><strong>${s.waiting}</strong><span>waiting on</span></div><div class="stat"><strong>${s.projects}</strong><span>active projects</span></div></section><section class="layout"><div class="col"><section class="panel"><div class="panel-head"><div><div class="eyebrow">TODAY</div><h2>Today's Focus</h2></div><div class="filters"><button class="filter ${state.focusFilter==='all'?'active':''}" data-filter="all">All</button><button class="filter ${state.focusFilter==='priority'?'active':''}" data-filter="priority">Priority</button><button class="filter ${state.focusFilter==='creative'?'active':''}" data-filter="creative">Creative</button><button class="filter ${state.focusFilter==='work'?'active':''}" data-filter="work">Work</button></div></div><div class="focus-list">${renderFocus(f)}</div></section><section class="panel"><button class="collapse" id="connectionToggle"><span><span class="eyebrow">CONNECTIONS</span><strong>Project Connection Map</strong><small>Collapsed by default. Open it when you want the wider context.</small></span><span>${state.connectionOpen?'−':'＋'}</span></button>${state.connectionOpen?renderConnection(f[0]):''}</section><section class="panel"><div class="panel-head"><div><div class="eyebrow">PROJECTS</div><h2>Projects Overview</h2></div><button class="filter" data-go-projects>View all</button></div><div class="project-grid">${renderProjectCards(activeProjects().sort((a,b)=>a.priority-b.priority).slice(0,6))}</div></section></div><aside class="col side"><section class="panel"><div class="eyebrow">NEEDS ATTENTION</div><h3>Blockers & decisions</h3><div class="mini-list">${renderAttention()}</div></section><section class="panel"><div class="eyebrow">WAITING</div><h3>Waiting on</h3><div class="mini-list">${renderWaiting()}</div></section><section class="panel"><div class="eyebrow">RECENT</div><h3>Recently completed</h3><div class="mini-list">${renderRecent()}</div></section></aside></section></div>`}
function renderFocus(list){let f=list;if(state.focusFilter==='priority')f=f.filter(t=>t.priority===1);if(state.focusFilter==='creative')f=f.filter(t=>/God's Contraband|Collaborators/i.test(t.area));if(state.focusFilter==='work')f=f.filter(t=>!/God's Contraband|Collaborators/i.test(t.area));return f.length?f.map(renderTaskCard).join(''):'<div class="empty">No focus tasks match this view.</div>'}
function renderTaskCard(t){const path=taskPath(t);return `<article class="task" style="--color:${colorForTask(t)}"><button class="check" data-complete="${esc(t.id)}">✓</button><button class="task-main" data-task="${esc(t.id)}"><div class="task-title">${esc(t.title)}</div><div class="breadcrumb">${esc(t.area)}${path.length?' → '+path.map(esc).join(' → '):''}</div><div class="task-meta"><span class="tag">${esc(contextMeta(t))}</span>${unlockCount(t)?`<span class="tag">Unlocks ${unlockCount(t)}</span>`:''}${t.waitingOn?`<span class="tag">Waiting: ${esc(t.waitingOn)}</span>`:''}</div></button><span class="priority p${t.priority}">${priorityLabel(t.priority)}</span></article>`}
function renderConnection(t){if(!t)return '<div class="connection"><div class="empty">No current task selected.</div></div>';const nodes=[{k:'Current task',v:t.title},...taskPath(t).map((v,i,a)=>({k:i===a.length-1?'Outcome':'Connected step',v}))];return `<div class="connection"><div class="connection-track">${nodes.map((n,i)=>`${i?'<span class="arrow">→</span>':''}<div class="node"><span class="eyebrow">${n.k}</span><strong>${esc(n.v)}</strong></div>`).join('')}</div></div>`}
function renderProjectCards(ps){return ps.map(p=>{const prog=projectProgress(p),active=projectActiveCount(p);return `<button class="project-card" style="--color:${p.color||'#62d6ff'}" data-project="${esc(p.id)}"><div class="eyebrow">${esc(p.area||'Project')}</div><h4>${esc(p.title)}</h4><p>${esc(p.summary||goal(p.goalId)?.title||'')}</p><div class="bar"><span style="width:${prog}%"></span></div><div class="project-foot"><span>${prog}% complete</span><span>${active} active</span></div></button>`}).join('')}
function renderAttention(){const items=openTasks().filter(t=>t.priority===1||unlockCount(t)>=2).sort((a,b)=>todayScore(b)-todayScore(a)).slice(0,4);return items.map(t=>`<button class="mini task-main" data-task="${esc(t.id)}"><strong>${esc(t.title)}</strong><small>${unlockCount(t)?`Unlocks ${unlockCount(t)} downstream · `:''}${esc(project(t.projectId)?.title||t.area)}</small></button>`).join('')||'<div class="empty">No urgent blockers.</div>'}
function renderWaiting(){const items=tasks().filter(t=>t.status==='Waiting'||t.waitingOn).filter(t=>t.status!=='Done').slice(0,5);return items.map(t=>`<button class="mini task-main" data-task="${esc(t.id)}"><strong>${esc(t.waitingOn||t.title)}</strong><small>${esc(t.title)}</small></button>`).join('')||'<div class="empty">Nothing waiting.</div>'}
function renderRecent(){const items=tasks().filter(t=>t.status==='Done').sort((a,b)=>String(b.completedAt||b.updatedAt).localeCompare(String(a.completedAt||a.updatedAt))).slice(0,4);return items.map(t=>`<button class="mini task-main" data-task="${esc(t.id)}"><strong>${esc(t.title)}</strong><small>${esc(project(t.projectId)?.title||t.area)}</small></button>`).join('')||'<div class="empty">No completed tasks yet.</div>'}
function renderProjectsPage(){const ps=activeProjects().sort((a,b)=>a.priority-b.priority).filter(p=>!state.query||[p.title,p.area,p.summary,goal(p.goalId)?.title].filter(Boolean).join(' ').toLowerCase().includes(state.query.toLowerCase()));return `<div class="page"><div class="page-header"><div class="eyebrow">PROJECTS</div><h1>Projects Overview</h1><p>Open a project to switch between what is most pressing and the true order of operations.</p></div><div class="project-page-grid">${renderProjectCards(ps)}</div></div>`}
function renderTaskListPage(title,desc,list){const filtered=list.filter(matchesQuery);return `<div class="page"><div class="page-header"><div class="eyebrow">TASKS</div><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><section class="panel"><div class="all-tasks">${filtered.length?filtered.map(t=>`<div class="list-row"><span class="status-dot ${t.status==='Waiting'?'waiting':t.status==='Done'?'done':''}"></span><button class="title-btn" data-task="${esc(t.id)}"><strong>${esc(t.title)}</strong><div class="breadcrumb">${esc(project(t.projectId)?.title||t.area)} · ${esc(t.status)}</div></button><span class="priority p${t.priority}">${priorityLabel(t.priority)}</span></div>`).join(''):'<div class="empty">Nothing here right now.</div>'}</div></section></div>`}

function bindView(){$$('[data-task]').forEach(b=>b.onclick=()=>openTask(b.dataset.task));$$('[data-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.project));$$('[data-complete]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await mutate('completeTask',{taskId:b.dataset.complete})});$$('[data-filter]').forEach(b=>b.onclick=()=>{state.focusFilter=b.dataset.filter;render()});$('#connectionToggle')?.addEventListener('click',()=>{state.connectionOpen=!state.connectionOpen;render()});$('[data-go-projects]')?.addEventListener('click',()=>{state.view='projects';render()})}
function populateProjectSelects(){const opts=projects().filter(p=>!p.archived).sort((a,b)=>a.title.localeCompare(b.title)).map(p=>`<option value="${esc(p.id)}">${esc(p.area)} — ${esc(p.title)}</option>`).join('');$('#newProject').innerHTML=opts;$('#taskProjectInput').innerHTML=opts}
async function openTask(id){const t=tasks().find(x=>x.id===id);if(!t)return;state.selectedTask=id;populateProjectSelects();$('#taskDialogEyebrow').textContent=`${t.id} · ${t.area}`;$('#taskTitleInput').value=t.title;$('#taskProjectInput').value=t.projectId||'';$('#taskPriorityInput').value=String(t.priority);$('#taskStatusInput').value=t.status;$('#taskDueInput').value=t.dueText||'';$('#taskNextInput').value=t.nextAction||'';$('#taskWaitingInput').value=t.waitingOn||'';$('#taskNotesInput').value=t.notes||'';const dep=dependencyTitles(t),unlock=tasks().filter(x=>(x.dependsOn||[]).includes(t.id)).map(x=>x.title);$('#taskContext').innerHTML=`<div class="context-box"><small>Path</small><span>${esc(taskPath(t).join(' → ')||'No project path yet')}</span></div><div class="context-box"><small>Requires</small><span>${esc(dep.join(', ')||'No task dependency')}</span></div><div class="context-box"><small>Unlocks</small><span>${esc(unlock.join(', ')||'No downstream task')}</span></div><div class="context-box"><small>People / source</small><span>${esc([...(t.people||[]),t.source].filter(Boolean).join(', ')||'—')}</span></div>`;$('#taskToggleDone').textContent=t.status==='Done'?'Reopen task':'✓ Mark complete';$('#taskDialog').showModal()}
async function saveSelectedTask(){const id=state.selectedTask;if(!id)return;await mutate('updateTask',{taskId:id,patch:{title:$('#taskTitleInput').value.trim(),projectId:$('#taskProjectInput').value||null,priority:Number($('#taskPriorityInput').value),status:$('#taskStatusInput').value,dueText:$('#taskDueInput').value.trim(),nextAction:$('#taskNextInput').value.trim(),waitingOn:$('#taskWaitingInput').value.trim(),notes:$('#taskNotesInput').value.trim()}});$('#taskDialog').close()}
async function toggleSelectedTask(){const t=tasks().find(x=>x.id===state.selectedTask);if(!t)return;await mutate(t.status==='Done'?'reopenTask':'completeTask',{taskId:t.id});$('#taskDialog').close()}
function projectSteps(p){const childIds=[p.id,...projects().filter(x=>x.parentProjectId===p.id).map(x=>x.id)];let list=tasks().filter(t=>childIds.includes(t.projectId));const ms=milestones().filter(m=>childIds.includes(m.projectId)).sort((a,b)=>(a.order||99)-(b.order||99));if(ms.length){const out=[];for(const m of ms){const mt=list.filter(t=>t.milestoneId===m.id).sort((a,b)=>statusWeight(a.status)-statusWeight(b.status)||a.priority-b.priority);if(mt.length)out.push(...mt)}out.push(...list.filter(t=>!t.milestoneId));list=[...new Map(out.map(t=>[t.id,t])).values()]}return list}
function openProject(id){const p=project(id);if(!p)return;state.selectedProject=id;state.projectMode='priority';renderProjectDialog();$('#projectDialog').showModal()}
function renderProjectDialog(){const p=project(state.selectedProject);if(!p)return;const list=projectSteps(p),prog=projectProgress(p);$('#projectArea').textContent=p.area;$('#projectTitle').textContent=p.title;$('#projectSummary').textContent=p.summary||goal(p.goalId)?.title||'';$('#projectProgress').textContent=`${prog}%`;$$('[data-project-mode]').forEach(b=>b.classList.toggle('active',b.dataset.projectMode===state.projectMode));let html='';if(state.projectMode==='priority'){const ranked=list.filter(t=>t.status!=='Done'&&t.status!=='Backlog').sort((a,b)=>todayScore(b)-todayScore(a));html=`<div class="priority-list">${ranked.length?ranked.map((t,i)=>`<button type="button" class="priority-row task-main" data-task="${esc(t.id)}"><span>${esc(t.title)}</span><span class="priority p${t.priority}">${i===0?'Now':i<3?'Next':'Later'}</span></button>`).join(''):'<div class="empty">No active tasks.</div>'}</div>`}else if(state.projectMode==='sequence'){html=`<div class="sequence">${list.length?list.map((t,i)=>`${i?'<span class="arrow">→</span>':''}<button type="button" class="step task-main ${i===0&&t.status!=='Done'?'current':''}" data-task="${esc(t.id)}"><span class="eyebrow">${esc(t.status)}</span><strong>${esc(t.title)}</strong></button>`).join(''):'<div class="empty">No tasks yet.</div>'}</div>`}else{const cols=['Open','In Progress','Waiting','Done'];html=`<div class="board">${cols.map(c=>`<div class="board-col"><strong>${c}</strong>${list.filter(t=>t.status===c).map(t=>`<button type="button" class="board-item task-main" data-task="${esc(t.id)}">${esc(t.title)}</button>`).join('')}</div>`).join('')}</div>`}$('#projectBody').innerHTML=html;$$('#projectBody [data-task]').forEach(b=>b.onclick=()=>openTask(b.dataset.task))}
async function mutate(action,payload){setSync('Saving…');try{const result=await api(action,payload);state.data=result.state;setSync('Saved',true);render()}catch(e){console.error(e);setSync('Could not save. Refresh and try again.');throw e}}
function setSync(text,autoHide=false){const b=$('#syncBanner');b.textContent=text;b.hidden=false;if(autoHide)setTimeout(()=>b.hidden=true,1200)}

async function init(){try{state.data=await api();populateProjectSelects();render()}catch(e){console.error(e);$('#viewRoot').innerHTML=`<div class="page"><section class="panel"><h2>Could not load the private task database.</h2><p style="color:var(--muted)">The app is deployed, but its private storage is not connected yet.</p></section></div>`;setSync('Private storage connection error.')}
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(!b)return;state.view=b.dataset.view;render()});$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim();render()});$('#quickAddBtn').onclick=()=>{populateProjectSelects();$('#newTaskDialog').showModal()};$('#newTaskClose').onclick=$('#newTaskCancel').onclick=()=>$('#newTaskDialog').close();$('#newTaskForm').onsubmit=async e=>{e.preventDefault();const p=project($('#newProject').value);await mutate('createTask',{task:{title:$('#newTitle').value.trim(),projectId:p?.id||null,goalId:p?.goalId||null,area:p?.area||'Inbox',priority:Number($('#newPriority').value),status:'Open',nextAction:$('#newNext').value.trim(),source:'Task Manager'}});e.target.reset();$('#newTaskDialog').close()};$('#saveTaskBtn').onclick=saveSelectedTask;$('#taskToggleDone').onclick=toggleSelectedTask;$$('[data-project-mode]').forEach(b=>b.onclick=()=>{state.projectMode=b.dataset.projectMode;renderProjectDialog()});}
init();
