function pushEdit(text,type='system'){const d=document.createElement('div');d.className=`msg ${type}`;d.textContent=text;document.getElementById('editLog').appendChild(d);document.getElementById('editLog').scrollTop=99999}
function executeEdit(q){q=q.trim();if(!q)return;pushEdit(q,'user');const low=q.toLowerCase();let m;
 if(low.includes('hub view')||low.includes('creative hubs')){snapshot('switch view');setView('hubs');pushEdit('Switched to Creative Hubs.','change');return}
 if(low.includes('relationship view')){snapshot('switch view');setView('relationship');pushEdit('Switched to Relationship View.','change');return}
 if(low.includes('show only musicians')){snapshot('filter musicians');currentFilter='Musicians';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='Musicians'));render();pushEdit('Showing only musicians.','change');return}
 if(low.includes('show all')){snapshot('show all');currentFilter='All';document.querySelectorAll('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter==='All'));render();pushEdit('Showing the full network.','change');return}
 if(low.includes('hide the right sidebar')||low.includes('hide right sidebar')){snapshot('hide right sidebar');appShell.classList.add('right-hidden');pushEdit('Right sidebar hidden.','change');return}
 if(low.includes('show the right sidebar')||low.includes('show right sidebar')){snapshot('show right sidebar');appShell.classList.remove('right-hidden');pushEdit('Right sidebar shown.','change');return}
 m=q.match(/change\s+(.+?)'?s role to\s+(.+)/i);if(m){const n=findNode(m[1]);if(!n){pushEdit('I could not confidently match that profile.','system');return}snapshot(`change ${n.name} role`);n.role=m[2].trim();persist();render();if(selectedId===n.id)showProfile(n.id);pushEdit(`Changed ${n.name}'s role to ${n.role}.`,'change');return}
 m=q.match(/add ipi\s+([\w-]+)\s+to\s+(.+)/i);if(m){const n=findNode(m[2]);if(!n){pushEdit('I could not confidently match that profile.','system');return}snapshot(`add IPI to ${n.name}`);n.ipi=m[1];persist();if(selectedId===n.id)showProfile(n.id);pushEdit(`Added IPI ${m[1]} to ${n.name}.`,'change');return}
 m=q.match(/move\s+(.+?)\s+closer to\s+(.+)/i);if(m){const a=findNode(m[1]),b=findNode(m[2]);if(!a||!b){pushEdit('I could not confidently match both profiles.','system');return}snapshot(`move ${a.name} closer to ${b.name}`);const pb=relationshipPos[b.id]||basePos(b),pa=relationshipPos[a.id]||basePos(a);relationshipPos[a.id]=[pb[0]+(pa[0]-pb[0])*.48,pb[1]+(pa[1]-pb[1])*.48];persist();Object.keys(motion).forEach(k=>delete motion[k]);render();pushEdit(`Moved ${a.name} closer to ${b.name} in Relationship View.`,'change');return}
 m=q.match(/(?:focus|open|select)\s+(?:on\s+)?(.+)/i);if(m){const n=findNode(m[1]);if(n){showProfile(n.id);appShell.classList.remove('right-hidden');pushEdit(`Opened ${n.name}.`,'change');return}}
 pushEdit('I understood this as a network edit, but this static demo does not have that command yet. The production AI layer will translate broader requests into structured, reviewable changes.','system')}
function answer(q){q=q.trim();if(!q)return;document.querySelectorAll('.node').forEach(x=>x.classList.remove('ai-highlight'));const low=q.toLowerCase();let picks=[],title='Network answer',reason='';if(low.includes('writing camp')&&low.includes('free')){picks=['cam','balam','mempho','camille'];reason='These profiles combine strong writing-room fit, rhythm/harmony coverage, and direct or warm paths around Free.'}else if(low.includes('bridge')){picks=nodes.filter(n=>n.type==='bridge').map(n=>n.id);reason='Bridge nodes connect otherwise separate hubs or scenes.'}else if(low.includes('produces')&&low.includes('keys')){picks=nodes.filter(n=>/producer/i.test(n.role)&&/keys/i.test(n.role)).map(n=>n.id);reason='Matched profiles whose role text includes both production and keys.'}else if(low.includes('upcoming show')||low.includes('show coming')){picks=DEMO_EVENTS.map(e=>e.person);reason='This is the event-activity layer. Real integrations can replace the placeholder data.'}else{const words=low.split(/\s+/).filter(w=>w.length>3);picks=nodes.filter(n=>words.some(w=>[n.name,n.artist,n.role,n.hub,...n.tags].filter(Boolean).join(' ').toLowerCase().includes(w))).slice(0,6).map(n=>n.id);reason=picks.length?'Matched your question against names, roles, hubs and tags.':'No strong structured match yet.'}picks.forEach(id=>{const el=viewport.querySelector(`[data-id="${CSS.escape(id)}"]`);if(el)el.classList.add('ai-highlight')});const names=picks.map(id=>nodes.find(n=>n.id===id)?.name).filter(Boolean);document.getElementById('askAnswer').innerHTML=`<h3>${title}</h3><div>${names.length?names.join(' · '):'No strong match yet.'}</div><div class="reason">${reason}</div><div class="evidence">Prototype answer from the map’s structured data; private relationship assessments remain user-authored.</div>`}