const clone=x=>JSON.parse(JSON.stringify(x));
let nodes=clone(BASE_NODES);const savedCustom=JSON.parse(localStorage.getItem('cn_custom_profiles')||'[]');nodes.push(...savedCustom);
const savedOverrides=JSON.parse(localStorage.getItem('cn_profile_overrides')||'{}');nodes.forEach(n=>Object.assign(n,savedOverrides[n.id]||{}));
let edges=clone(BASE_EDGES),relationshipPos=Object.assign({},clone(RELATIONSHIP_POS),JSON.parse(localStorage.getItem('cn_relationship_pos')||'{}'));
let currentView='relationship',currentFilter='All',selectedId=null,searchTerm='';
let camera={x:0,y:0,scale:1},drag=null;const motion={},undoStack=[];
const appShell=document.getElementById('appShell'),svg=document.getElementById('map'),viewport=document.getElementById('viewport'),profile=document.getElementById('profile');
const NS='http://www.w3.org/2000/svg';const svgEl=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
function initials(name){return String(name).split(/\s+/).map(x=>x[0]).join('').replace(/\W/g,'').slice(0,2).toUpperCase()||'?'}
function customOffsets(){const counts={};const out={};nodes.forEach(n=>{const i=counts[n.hub]||0;counts[n.hub]=i+1;const a=i*2.25,r=n.hub==='Center'?0:42+(i%2)*11;out[n.id]=[Math.cos(a)*r,Math.sin(a)*r]});return out}
function basePos(n){if(currentView==='relationship')return relationshipPos[n.id]||[500,360];const c=HUB_CENTERS[n.hub]||[500,360],o=customOffsets()[n.id]||[0,0];return[c[0]+o[0],c[1]+o[1]]}
function visible(n){if(currentFilter!=='All'&&!n.tags.includes(currentFilter))return false;if(searchTerm){const hay=[n.name,n.artist,n.role,n.hub,...n.tags].filter(Boolean).join(' ').toLowerCase();if(!hay.includes(searchTerm))return false}return true}
function state(n){if(!motion[n.id]){const p=basePos(n);motion[n.id]={x:p[0],y:p[1],vx:0,vy:0,phase:Math.random()*Math.PI*2}}return motion[n.id]}
function applyCamera(){viewport.setAttribute('transform',`translate(${camera.x} ${camera.y}) scale(${camera.scale})`)}
function render(){viewport.innerHTML='';
 if(currentView==='relationship')[[125,'Core'],[235,'Working Network'],[345,'Extended / Orbit']].forEach(([r,label])=>{viewport.appendChild(svgEl('circle',{cx:500,cy:360,r,class:'ring'}));const t=svgEl('text',{x:500,y:360-r+14,'text-anchor':'middle',class:'ringlabel'});t.textContent=label;viewport.appendChild(t)})
 else Object.entries(HUB_CENTERS).filter(([h])=>h!=='Center').forEach(([h,c])=>{const members=nodes.filter(n=>n.hub===h&&visible(n));if(!members.length)return;const rad=Math.max(64,58+members.length*5);viewport.appendChild(svgEl('circle',{cx:c[0],cy:c[1],r:rad,class:`hubfield ${h==="God's Contraband"?'core':''}`}));const lab=svgEl('text',{x:c[0],y:c[1]-rad-10,'text-anchor':'middle',class:'hublabel'});lab.textContent=h;lab.onclick=()=>{searchTerm=h.toLowerCase();document.getElementById('search').value=h;render()};viewport.appendChild(lab);const count=svgEl('text',{x:c[0],y:c[1]-rad+4,'text-anchor':'middle',class:'hubcount'});count.textContent=`${members.length} members`;viewport.appendChild(count)});
 edges.forEach(([a,b,kind])=>{const na=nodes.find(n=>n.id===a),nb=nodes.find(n=>n.id===b);if(!na||!nb||!visible(na)||!visible(nb))return;const pa=state(na),pb=state(nb);let cls=`edge ${kind==='future'?'future':(na.type==='bridge'||nb.type==='bridge')?'bridge':''}`;if(currentView==='hubs')cls+=na.hub===nb.hub?' hub-local':' hub-cross';viewport.appendChild(svgEl('line',{x1:pa.x,y1:pa.y,x2:pb.x,y2:pb.y,class:cls,'data-a':a,'data-b':b}))});
 nodes.filter(visible).forEach(n=>{const s=state(n),g=svgEl('g',{class:`node ${n.type||''} ${selectedId===n.id?'selected':''}`,transform:`translate(${s.x},${s.y})`,'data-id':n.id});const fill=n.type==='core'?'#332d22':n.type==='bridge'?'#1b2a3c':n.type==='hubnode'?'#183229':'#1b212c';g.appendChild(svgEl('circle',{r:n.r||22,fill}));const txt=svgEl('text',{x:0,y:4,'text-anchor':'middle',fill:'#dde4ed','font-size':n.r>27?12:10,'font-weight':'800'});txt.textContent=initials(n.name);g.appendChild(txt);const nm=svgEl('text',{x:0,y:(n.r||22)+15,'text-anchor':'middle',class:'name'});nm.textContent=n.name;g.appendChild(nm);const role=svgEl('text',{x:0,y:(n.r||22)+27,'text-anchor':'middle',class:'role'});role.textContent=currentView==='hubs'?n.hub:n.role;g.appendChild(role);if(DEMO_EVENTS.some(e=>e.person===n.id)){const eb=svgEl('text',{x:0,y:-(n.r||22)-8,'text-anchor':'middle',class:'event-badge'});eb.textContent='UPCOMING';g.appendChild(eb)}g.onclick=()=>showProfile(n.id);viewport.appendChild(g)});applyCamera()}
function animate(){const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;nodes.forEach((n,i)=>{const s=state(n),p=basePos(n),stable=n.id==='uh'?0.055:0.025;const t=performance.now()/1000;const amp=reduce?0:n.id==='uh'?2:5+(i%4)*1.4;const tx=p[0]+Math.sin(t*.20+s.phase)*amp,ty=p[1]+Math.cos(t*.17+s.phase*.7)*amp;s.vx+=(tx-s.x)*stable;s.vy+=(ty-s.y)*stable;s.vx*=.91;s.vy*=.91;s.x+=s.vx;s.y+=s.vy;const g=viewport.querySelector(`[data-id="${CSS.escape(n.id)}"]`);if(g)g.setAttribute('transform',`translate(${s.x},${s.y})`)});viewport.querySelectorAll('line[data-a]').forEach(line=>{const a=motion[line.dataset.a],b=motion[line.dataset.b];if(a&&b){line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y)}});requestAnimationFrame(animate)}
function showProfile(id){selectedId=id;const n=nodes.find(x=>x.id===id);if(!n)return;render();const notes=JSON.parse(localStorage.getItem('cn_notes')||'{}');const ev=DEMO_EVENTS.filter(e=>e.person===id);profile.innerHTML=`<div class="avatar">${n.photo?`<img src="${n.photo}" alt="">`:initials(n.name)}</div><h2>${n.name}</h2>${n.artist?`<div class="alias">${n.artist}</div>`:''}<div class="cards"><div class="card"><div class="k">Role</div><div class="v">${n.role}</div></div><div class="card"><div class="k">Hub</div><div class="v">${n.hub}</div></div><div class="card"><div class="k">Connection to you</div><div class="v">${n.relationship||'Not yet defined'}</div></div><div class="card"><div class="k">Node type</div><div class="v">${n.type||'Person'}</div></div></div><div class="bio">${n.bio||''}</div><div class="tags">${(n.tags||[]).filter(x=>x!=='All').map(t=>`<span class="tag">${t}</span>`).join('')}</div><div class="profile-section"><h3>Connection to you</h3><div class="bio">${n.connection||'Needs more context.'}</div></div><div class="profile-section"><h3>Connection to larger network</h3><div class="bio">${n.network||'Needs more context.'}</div></div>${n.pro||n.ipi?`<div class="profile-section"><h3>Rights / publishing</h3><div class="cards"><div class="card"><div class="k">PRO</div><div class="v">${n.pro||'—'}</div></div><div class="card"><div class="k">IPI / CAE</div><div class="v">${n.ipi||'—'}</div></div></div></div>`:''}<div class="links">${n.instagram?`<a target="_blank" rel="noopener" href="${n.instagram}">Instagram ↗</a>`:''}${n.spotify?`<a target="_blank" rel="noopener" href="${n.spotify}">Spotify ↗</a>`:''}${n.link?`<a target="_blank" rel="noopener" href="${n.link}">Portfolio / link ↗</a>`:''}</div>${ev.length?`<div class="profile-section"><h3>Upcoming</h3>${ev.map(e=>`<div class="event-card"><div class="date">${e.date}</div><div class="title">${e.title}</div><div class="meta">${e.meta}</div></div>`).join('')}</div>`:''}<div class="profile-section"><h3>Private browser note</h3><textarea class="note-box" id="profileNote" placeholder="Notes stay in this browser…">${notes[id]||''}</textarea><button class="save-note" id="saveProfileNote">Save note</button></div>`;document.getElementById('saveProfileNote').onclick=()=>{const d=JSON.parse(localStorage.getItem('cn_notes')||'{}');d[id]=document.getElementById('profileNote').value;localStorage.setItem('cn_notes',JSON.stringify(d))}}
function setView(view){currentView=view;document.querySelectorAll('.viewbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.getElementById('status').textContent=view==='relationship'?'Relationship view':'Creative hubs';document.getElementById('viewExplainer').innerHTML=view==='relationship'?'<strong>Relationship View</strong><br>Who is close to you? Distance reflects direct relationship strength.':'<strong>Creative Hubs</strong><br>Where does everyone belong? Cross-hub lines reveal bridge relationships.';Object.values(motion).forEach(s=>{s.vx*=.2;s.vy*=.2});render()}
function persist(){const overrides={};nodes.filter(n=>BASE_NODES.some(b=>b.id===n.id)).forEach(n=>overrides[n.id]={role:n.role,pro:n.pro,ipi:n.ipi});localStorage.setItem('cn_profile_overrides',JSON.stringify(overrides));localStorage.setItem('cn_relationship_pos',JSON.stringify(relationshipPos));localStorage.setItem('cn_custom_profiles',JSON.stringify(nodes.filter(n=>!BASE_NODES.some(b=>b.id===n.id))))}
function snapshot(label){undoStack.push({label,nodes:clone(nodes),relationshipPos:clone(relationshipPos),filter:currentFilter,view:currentView,left:appShell.classList.contains('left-hidden'),right:appShell.classList.contains('right-hidden')});if(undoStack.length>20)undoStack.shift()}
function undo(){const s=undoStack.pop();if(!s){pushEdit('Nothing to undo yet.','system');return}nodes=s.nodes;relationshipPos=s.relationshipPos;currentFilter=s.filter;currentView=s.view;appShell.classList.toggle('left-hidden',s.left);appShell.classList.toggle('right-hidden',s.right);persist();render();if(selectedId)showProfile(selectedId);pushEdit(`Undid: ${s.label}`,'change')}
function findNode(name){const q=name.trim().toLowerCase().replace(/[“”"']/g,'');return nodes.find(n=>[n.name,n.artist,n.id].filter(Boolean).some(v=>{const x=String(v).toLowerCase();return x===q||x.includes(q)||q.includes(x)}))}
function openPanel(id){['askPanel','editPanel'].forEach(x=>document.getElementById(x).classList.toggle('hidden',x!==id));document.getElementById(id).classList.remove('hidden')}