const BASE_NODES=[
{id:'uh',name:'Ausar / uh_sar',artist:'uh_sar',role:'Producer · Artist · Arranger',hub:'Center',type:'core',r:34,tags:['All','Musicians','Producers'],relationship:'Self',connection:'Central creative node.',network:'Owner of the network.',bio:'Producer, artist, arranger, multi-instrumentalist and creative director.'},
{id:'addae',name:'Addae Madison',role:'Manager · Visuals · Connector',hub:'Visual / Management',type:'core',r:28,tags:['All','Visual','Connectors'],relationship:'Brother / core collaborator',connection:'Brother and core creative-support node.',network:'Connects the visual/management lane to multiple artist relationships.',bio:'Helps with visuals, gear, coordination, introductions and unofficial management.'},
{id:'jordan',name:'Jordan Betine',role:'Director · Filmmaker',hub:'Visual / Management',r:22,tags:['All','Visual'],relationship:'Friend / active collaborator',connection:'Friend and filmmaker collaborator.',network:'Visual / Management hub.',bio:'Filmmaker collaborating on the Unstoppable music video.'},
{id:'cam',name:'Cam',artist:'nevermetahuman',role:'Drummer · Singer · Multi-inst.',hub:'Professor What Trio',type:'bridge',r:29,tags:['All','Writing Camps','Musicians',"God's Contraband"],relationship:'Direct collaborator',connection:'Rehearsed with God’s Contraband and fits important writing rooms.',network:'Bridge between Professor What Trio, GC, and future writing camps.',bio:'Elite drummer and multi-instrumentalist with strong feel; singer-songwriter potential.'},
{id:'balam',name:'Balam Garcia',role:'Guitar · Bass · Arrangement',hub:'Professor What Trio',r:25,tags:['All','Writing Camps','Musicians',"God's Contraband"],relationship:'Direct collaborator',connection:'Strong live and writing collaborator.',network:'Professor What Trio and GC bridge.',bio:'Guitar, bass, composition and arrangement. Strong writing-room fit.'},
{id:'drew',name:'Drew',artist:'drewofthedrew',role:'Bass · Production · Engineering',hub:'Professor What Trio',r:22,tags:['All','Musicians','Producers'],relationship:'Second-degree / developing',connection:'Developing direct relationship.',network:'Professor What Trio.',bio:'Elite musician in Professor What Trio with Balam and Cam.'},
{id:'free',name:'Free',role:'Singer · Writer · Artist',hub:'Delaware–Philly',type:'bridge',r:28,tags:['All','Writing Camps','Rising Artists',"God's Contraband"],relationship:'Direct collaborator / GC bridge',connection:'Appears on and performs with God’s Contraband.',network:'Bridge into Delaware/Philly via Zeke and adjacent artists.',spotify:'https://open.spotify.com/artist/4twpepGEgW66i8ZkhEg6yW',bio:'Strong natural rhythm and writing potential.'},
{id:'zeke',name:'ZekeUltra',artist:'ZekeUltra',role:'Artist · Writer',hub:'Delaware–Philly',r:23,tags:['All','Rising Artists'],relationship:'Warm second-degree through Free',connection:'Warm path through Free.',network:'Delaware/Philly artist scene.',spotify:'https://open.spotify.com/artist/66rjQYZAzWZ9n933ytcoTg',bio:'Close friend/collaborator of Free.'},
{id:'camille',name:'Camille',role:'Songwriter',hub:'R&B Writing Orbit',type:'core',r:27,tags:['All','Writing Camps'],relationship:'Good friend / writing partner',connection:'Good friend and developing writing partner.',network:'R&B writing orbit with paths toward artists such as Brit.',bio:'Focused on R&B songwriting and placements.'},
{id:'brit',name:'Brit',artist:'quachmamma',role:'R&B Artist',hub:'R&B Writing Orbit',r:22,tags:['All','Rising Artists'],relationship:'Warm potential collaborator',connection:'Warm path through overlapping circles.',network:'R&B writing orbit.',spotify:'https://open.spotify.com/artist/2MdJ6HaAJ9lvopGsirEuz6',bio:'Warm potential collaborator in overlapping friend circles with Camille.'},
{id:'okay',name:'okay coleman!',artist:'okay coleman!',role:'Artist · Producer · Multi-inst.',hub:'R&B Writing Orbit',r:21,tags:['All','Rising Artists','Musicians','Producers'],relationship:'Indirect / aspirational warm path',connection:'Adjacent through Brit/Camille.',network:'R&B writing orbit.',spotify:'https://open.spotify.com/artist/2kAc58JeMNRXTVm3sVHrSN',bio:'Adjacent artist connection through the Brit/Camille network.'},
{id:'sockjus',name:'Sockjus',artist:'Sockjus',role:'Artist · Live Performer',hub:'Baw$ / Sockjus Orbit',type:'bridge',r:27,tags:['All','Rising Artists'],relationship:'Direct collaborator',connection:'Multiple songs with Ausar.',network:'Bridge into the Baw$/John creative-house orbit.',instagram:'https://www.instagram.com/sockjus_/',spotify:'https://open.spotify.com/artist/00N2uEeIU49XMhjJmduP3Y',bio:'Direct collaborator with live-show potential.'},
{id:'john',name:'John',artist:'theotherjohnmayer',role:'Guitar · Producer · Multi-inst.',hub:'Baw$ / Sockjus Orbit',r:23,tags:['All','Writing Camps','Musicians','Producers'],relationship:'Direct collaborator',connection:'Co-produced You Said It.',network:'Creative-house orbit with Sockjus and Baw$.',instagram:'https://www.instagram.com/theotherjohnmayer/',bio:'Talented guitarist, producer and multi-instrumentalist.'},
{id:'baws',name:'Baw$',artist:'Baw$',role:'Producer · Artist · Connector',hub:'Baw$ / Sockjus Orbit',type:'bridge',r:27,tags:['All','Writing Camps','Rising Artists','Producers','Connectors'],relationship:'Warm connection via Addae',connection:'Warm direct path through Addae.',network:'Connector in the Sockjus/John creative-house orbit.',instagram:'https://www.instagram.com/baws._/',bio:'Producer, artist and connector.'},
{id:'mempho',name:'Mempho',artist:'Mempho',role:'Producer · Rapper · Drums · Keys',hub:'Baw$ / Sockjus Orbit',type:'bridge',r:27,tags:['All','Writing Camps','Musicians','Rising Artists','Producers'],relationship:'Direct warm connection',connection:'Warm connection through Addae and shared orbit.',network:'Bridge between writing rooms and the Baw$/Sockjus orbit.',bio:'Versatile producer/artist with drums, keys and rap.'},
{id:'nick',name:'Nick Bison',artist:'Nick Bison',role:'Versatile Artist',hub:'Baw$ / Sockjus Orbit',r:20,tags:['All','Rising Artists'],relationship:'Second-degree',connection:'Path through Baw$ and Mempho.',network:'Baw$/Sockjus orbit.',instagram:'https://www.instagram.com/nick.bison/',bio:'Versatile artist in the same creative orbit.'},
{id:'joel',name:'Joel',role:'Trumpet · Horns · Engineer',hub:"Joel's DTLA Studio",type:'hubnode',r:23,tags:['All','Musicians'],relationship:'Direct specialist collaborator',connection:'Horn/woodwind and studio collaborator.',network:'Studio/resource node with live-room capability.',bio:'Elite musician and specialist collaborator; trumpet/woodwinds and engineering.'},
{id:'jonah',name:'Jonah',role:'Multi-inst. · Engineer · Songwriter',hub:'Jonah Studio',type:'hubnode',r:23,tags:['All','Writing Camps','Musicians','Producers'],relationship:'Direct collaborator',connection:'Past multi-day writing session.',network:'Studio hub and songwriter/engineer resource.',bio:'Multi-instrumentalist, vocalist, recording engineer and songwriter.'},
{id:'dante',name:'Dante',role:'Rapper · Writer',hub:"God's Contraband",type:'core',r:27,tags:['All',"God's Contraband"],relationship:'Core / founding collaborator',connection:'Founding/core God’s Contraband collaborator.',network:'Central God’s Contraband node.',bio:'Rapper, writer and live creative partner.'},
{id:'diontae',name:'Diontae',artist:'Son',role:'Rapper',hub:"God's Contraband",r:21,tags:['All',"God's Contraband"],relationship:'Direct collaborator',connection:'God’s Contraband collaborator.',network:'God’s Contraband hub.',instagram:'https://www.instagram.com/diontaes1mpson/',bio:'God’s Contraband rapper, also known as Son.'},
{id:'solomon',name:'Solomon',role:'Artist · Collaborator',hub:"God's Contraband",r:22,tags:['All',"God's Contraband",'Writing Camps'],relationship:'Direct collaborator',connection:'God’s Contraband contributor and broader collaborator.',network:'GC + future writing-room potential.',bio:'Detailed role and profile still to be filled out.'},
{id:'chris',name:'Chris',role:'Keys · Musician',hub:"God's Contraband",r:23,tags:['All',"God's Contraband",'Musicians'],relationship:'Direct collaborator',connection:'God’s Contraband keyboardist.',network:'God’s Contraband hub.',bio:'Elite keyboardist for God’s Contraband.'}
];
const BASE_EDGES=[['uh','addae',''],['uh','jordan',''],['addae','jordan','strong'],['uh','cam',''],['uh','balam',''],['cam','balam','strong'],['cam','drew','strong'],['balam','drew','strong'],['uh','free',''],['free','zeke','strong'],['uh','camille',''],['camille','brit','strong'],['brit','okay','future'],['uh','sockjus',''],['sockjus','john','strong'],['sockjus','baws','strong'],['baws','john','strong'],['baws','mempho','strong'],['mempho','nick','strong'],['uh','mempho',''],['addae','baws','strong'],['addae','sockjus',''],['addae','mempho',''],['uh','joel',''],['uh','jonah',''],['uh','dante',''],['uh','diontae',''],['uh','solomon',''],['uh','chris',''],['dante','diontae','strong'],['dante','solomon','strong'],['free','cam','future'],['free','balam','future'],['mempho','camille','future'],['mempho','free','future']];
const RELATIONSHIP_POS={uh:[500,360],addae:[365,250],jordan:[245,185],cam:[610,210],balam:[700,260],drew:[795,175],free:[655,385],zeke:[805,420],camille:[360,480],brit:[245,545],okay:[145,610],sockjus:[760,360],john:[845,285],baws:[850,430],mempho:[760,490],nick:[900,535],joel:[275,370],jonah:[235,445],dante:[480,525],diontae:[555,565],solomon:[415,570],chris:[515,600]};
const HUB_CENTERS={Center:[500,360],'Visual / Management':[225,190],'Professor What Trio':[720,180],'Delaware–Philly':[805,370],'R&B Writing Orbit':[220,550],'Baw$ / Sockjus Orbit':[815,510],"Joel's DTLA Studio":[335,385],'Jonah Studio':[310,500],"God's Contraband":[520,555]};
const RELEASES=[
{v:'GitHub v2',date:'2026-09-17',title:'Full feature restoration',notes:'Living motion, relationship/hub views, pan/zoom, collapsible panels, Ask Network, Talk + Edit, Add Profile, history, notes and activity layer.'},
{v:'GitHub v1',date:'2026-09-17',title:'Stable canonical baseline',notes:'Clean relationship/hub map published to GitHub Pages.'},
{v:'v17 prototype',date:'2026-09-17',title:'Solomon + conversational prototype',notes:'Last pre-GitHub ChatGPT artifact lineage.'}
];
const DEMO_EVENTS=[
{person:'sockjus',date:'Example',title:'Upcoming show data',meta:'Event integrations such as Partiful/JamBase can populate this later.'}
];