// UI wiring
document.querySelectorAll('.viewbtn').forEach(b=>b.onclick=()=>setView(b.dataset.view));
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));render()});
document.getElementById('search').oninput=e=>{searchTerm=e.target.value.trim().toLowerCase();render()};
document.getElementById('toggleLeft').onclick=()=>appShell.classList.toggle('left-hidden');document.getElementById('toggleRight').onclick=()=>appShell.classList.toggle('right-hidden');document.getElementById('fullMap').onclick=()=>{const full=appShell.classList.contains('left-hidden')&&appShell.classList.contains('right-hidden');appShell.classList.toggle('left-hidden',!full);appShell.classList.toggle('right-hidden',!full)};
document.getElementById('askBtn').onclick=()=>openPanel('askPanel');document.getElementById('editBtn').onclick=()=>openPanel('editPanel');
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).classList.add('hidden'));
document.getElementById('askSend').onclick=()=>answer(document.getElementById('askInput').value);document.getElementById('askInput').onkeydown=e=>{if(e.key==='Enter')document.getElementById('askSend').click()};document.querySelectorAll('.ask-suggestion').forEach(b=>b.onclick=()=>{document.getElementById('askInput').value=b.textContent;answer(b.textContent)});
document.getElementById('editSend').onclick=()=>{const i=document.getElementById('editInput');executeEdit(i.value);i.value=''};document.getElementById('editInput').onkeydown=e=>{if(e.key==='Enter')document.getElementById('editSend').click()};document.querySelectorAll('.edit-suggestion').forEach(b=>b.onclick=()=>executeEdit(b.textContent));document.getElementById('undoEdit').onclick=undo;
function openProfileModal(){document.getElementById('profileModal').classList.remove('hidden');setTimeout(()=>document.getElementById('newName').focus(),30)}document.getElementById('addProfileBtn').onclick=openProfileModal;document.getElementById('sidebarAdd').onclick=openProfileModal;
document.getElementById('saveProfile').onclick=()=>{const name=document.getElementById('newName').value.trim();if(!name){alert('Add a name first.');return}const id=`custom_${Date.now()}`;const type=document.getElementById('newType').value;const n={id,name,artist:document.getElementById('newArtist').value.trim(),role:document.getElementById('newRole').value.trim()||'Creative collaborator',hub:document.getElementById('newHub').value.trim()||'Extended Network',type:type==='studio'?'hubnode':'',r:21,tags:['All',type==='musician'?'Musicians':type==='filmmaker'?'Visual':type==='manager'?'Connectors':'Extended'],relationship:document.getElementById('newConnection').value.trim()||'Needs relationship context',connection:document.getElementById('newConnection').value.trim(),network:document.getElementById('newNetwork').value.trim(),bio:'Added locally in the browser.',pro:document.getElementById('newPRO').value.trim(),ipi:document.getElementById('newIPI').value.trim(),link:document.getElementById('newLink').value.trim()};nodes.push(n);relationshipPos[id]=[500+Math.cos(nodes.length)*260,360+Math.sin(nodes.length)*220];edges.push(['uh',id,'future']);persist();document.getElementById('profileModal').classList.add('hidden');Object.values(motion).forEach(s=>{s.vx*=.2;s.vy*=.2});render();showProfile(id)};
document.getElementById('historyBtn').onclick=()=>{document.getElementById('historyBody').innerHTML=RELEASES.map(r=>`<div class="history-item"><strong>${r.v} · ${r.title}</strong><p>${r.date}<br>${r.notes}</p></div>`).join('')+`<div class="history-item"><strong>GitHub is now the canonical version history</strong><p>Every future code update is a commit in the repository, so the live URL stays the same while old builds remain recoverable.</p></div>`;document.getElementById('historyModal').classList.remove('hidden')};
function zoom(f){camera.scale=Math.max(.55,Math.min(2.2,camera.scale*f));applyCamera()}document.getElementById('zoomIn').onclick=()=>zoom(1.15);document.getElementById('zoomOut').onclick=()=>zoom(.87);document.getElementById('zoomReset').onclick=()=>{camera={x:0,y:0,scale:1};applyCamera()};svg.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.08:.92)},{passive:false});svg.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};svg.classList.add('dragging');svg.setPointerCapture(e.pointerId)});svg.addEventListener('pointermove',e=>{if(!drag)return;camera.x=drag.cx+(e.clientX-drag.x);camera.y=drag.cy+(e.clientY-drag.y);applyCamera()});svg.addEventListener('pointerup',()=>{drag=null;svg.classList.remove('dragging')});
render();showProfile('uh');animate();